# -*- coding: utf-8 -*-
"""Ads Product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b2JeJTHZNDMFiJTt5muyInqvVb6fxmFX
"""

pip install kaggle

"""To download the dataset from Kaggle, you need to provide your Kaggle API credentials. Please follow these steps:

1. Go to [Kaggle](https://www.kaggle.com/).
2. Click on your profile picture in the top right corner and select "My Account".
3. Scroll down to the "API" section and click "Create New API Token". This will download a `kaggle.json` file.
4. Open the `kaggle.json` file with a text editor. It should contain your username and API key.
5. In Colab, go to the "Secrets" tab (🔑 icon on the left panel).
6. Add a new secret named `KAGGLE_USERNAME` and paste your Kaggle username as the value.
7. Add another secret named `KAGGLE_KEY` and paste your Kaggle API key as the value.
"""

import os
from google.colab import userdata

os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

# The command provided by the user needs to be executed as a shell command.
# This command will download the kernel's associated dataset files into the current directory.
!kaggle kernels pull yasserh/advertisement-budget-prediction-top-ml-models

# Unzip the downloaded archive (if it's a zip file)
# The name of the zip file is usually derived from the kernel name.

# First, check what files were downloaded
!ls -F

# Try to unzip the most likely file name or check for a .zip file
import glob
zip_files = glob.glob('*.zip')
if zip_files:
    print(f"Found zip file(s): {zip_files}. Unzipping the first one.")
    !unzip -o {zip_files[0]}
else:
    print("No zip file found. Listing contents again to check for directories.")

# List contents after unzipping to see the extracted files
!ls -F

# Read the content of the downloaded .ipynb file to inspect its structure and find data loading commands
import json

notebook_filename = 'advertisement-budget-prediction-top-ml-models.ipynb'

try:
    with open(notebook_filename, 'r') as f:
        notebook_content = json.load(f)

    print(f"Successfully loaded {notebook_filename}.")

    # Iterate through cells to find potential data loading commands
    data_loading_cells = []
    for cell in notebook_content.get('cells', []):
        if cell.get('cell_type') == 'code':
            source = ''.join(cell.get('source', []))
            if 'pd.read_csv' in source or 'pd.read_excel' in source or 'pd.read_json' in source:
                data_loading_cells.append(source)

    if data_loading_cells:
        print("\nFound potential data loading code snippets in the notebook:\n")
        for i, snippet in enumerate(data_loading_cells):
            print(f"--- Snippet {i+1} ---")
            print(snippet)
            print("---------------------")
    else:
        print("\nNo explicit 'pd.read_csv', 'pd.read_excel', or 'pd.read_json' found in code cells. The data might be in another format or loaded differently.")

except FileNotFoundError:
    print(f"Error: Notebook file '{notebook_filename}' not found.")
except json.JSONDecodeError:
    print(f"Error: Could not decode JSON from '{notebook_filename}'. It might be corrupted or not a valid notebook file.")

import kagglehub
import os

# Download latest version of the dataset
path = kagglehub.dataset_download("shreyanshverma27/brands-sales-and-ad-spend-data")

print("Path to dataset files:", path)

# List files in the downloaded directory to identify the CSV
print("Files in the downloaded dataset directory:")
for root, dirs, files in os.walk(path):
    for name in files:
        print(os.path.join(root, name))

import pandas as pd

# The dataset was downloaded to this path and named 'Brand_Sales_AdSpend_Data.csv'
dataset_path = '/root/.cache/kagglehub/datasets/shreyanshverma27/brands-sales-and-ad-spend-data/versions/1/Brand_Sales_AdSpend_Data.csv'

try:
    df = pd.read_csv(dataset_path)
    print("Dataset loaded successfully for inspection!")

    # Clean column names by stripping whitespace (including non-breaking spaces)
    df.columns = df.columns.str.strip().str.replace('\xa0', '')

    print("Column names cleaned.")
    display(df.head())
    print(f"Dataset shape: {df.shape}")
    print(f"Dataset columns: {df.columns.tolist()}")

    # Define features (X) and target (y) for ad spend prediction
    # Assuming numerical columns related to sales and other metrics are features
    # and 'Total Ad Spend' is the target.
    target_column = 'Total Ad Spend'
    feature_columns = ['Gross Sales', 'Net Sales', 'Total Sales', 'Order Count', 'Return Amount'] # Exclude 'Date', 'Brand Name', 'Country' for now

    # Ensure all identified columns exist in the DataFrame
    missing_cols = [col for col in [target_column] + feature_columns if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing expected columns in the dataset: {missing_cols}")

    X = df[feature_columns]
    y = df[target_column]

    print(f"\nTarget variable: {target_column}")
    print(f"Feature variables: {feature_columns}")
    print(f"Shape of features (X): {X.shape}")
    print(f"Shape of target (y): {y.shape}")

except FileNotFoundError:
    print(f"Error: '{dataset_path}' not found. Please ensure it was downloaded and extracted correctly.")
except Exception as e:
    print(f"An error occurred while loading or processing the dataset: {e}")

"""Sekarang data `Advertising Budget and Sales.csv` telah berhasil dimuat ke dalam DataFrame bernama `df`. Anda dapat mulai menganalisisnya dan membangun model Machine Learning. Bagaimana Anda ingin melanjutkan?"""

import kagglehub
import os

# Download latest version of the dataset
path = kagglehub.dataset_download("shreyanshverma27/brands-sales-and-ad-spend-data")

print("Path to dataset files:", path)

# List files in the downloaded directory to identify the CSV
print("Files in the downloaded dataset directory:")
for root, dirs, files in os.walk(path):
    for name in files:
        print(os.path.join(root, name))

import pandas as pd

# The dataset was downloaded to this path and named 'Brand_Sales_AdSpend_Data.csv'
dataset_path = '/root/.cache/kagglehub/datasets/shreyanshverma27/brands-sales-and-ad-spend-data/versions/1/Brand_Sales_AdSpend_Data.csv'

try:
    # Load the dataset into a pandas DataFrame without specific index_col, names, or skiprows
    # This is to inspect its structure and determine the correct parameters.
    df = pd.read_csv(dataset_path)
    print("Dataset loaded successfully for inspection!")
    display(df.head())
    print(f"Dataset shape: {df.shape}")
    print(f"Dataset columns: {df.columns.tolist()}")
except FileNotFoundError:
    print(f"Error: '{dataset_path}' not found. Please ensure it was downloaded and extracted correctly.")
except Exception as e:
    print(f"An error occurred while loading the dataset: {e}")

"""Sekarang data `Advertising Budget and Sales.csv` telah berhasil dimuat ke dalam DataFrame bernama `df`. Mari kita mulai menganalisis datanya untuk melihat apakah data ini dapat digunakan untuk membuat model prediksi pengeluaran iklan."""

# Display basic information about the DataFrame
display(df.info())

# Display descriptive statistics
display(df.describe())

# Check for missing values
display(df.isnull().sum())

import kagglehub
import os

# Download latest version of the dataset
path = kagglehub.dataset_download("shreyanshverma27/brands-sales-and-ad-spend-data")

print("Path to dataset files:", path)

# List files in the downloaded directory to identify the CSV
print("Files in the downloaded dataset directory:")
for root, dirs, files in os.walk(path):
    for name in files:
        print(os.path.join(root, name))

import pandas as pd

# The dataset was downloaded to this path and named 'Brand_Sales_AdSpend_Data.csv'
dataset_path = '/root/.cache/kagglehub/datasets/shreyanshverma27/brands-sales-and-ad-spend-data/versions/1/Brand_Sales_AdSpend_Data.csv'

try:
    # Load the dataset into a pandas DataFrame without specific index_col, names, or skiprows
    # This is to inspect its structure and determine the correct parameters.
    df = pd.read_csv(dataset_path)
    print("Dataset loaded successfully for inspection!")
    display(df.head())
    print(f"Dataset shape: {df.shape}")
    print(f"Dataset columns: {df.columns.tolist()}")
except FileNotFoundError:
    print(f"Error: '{dataset_path}' not found. Please ensure it was downloaded and extracted correctly.")
except Exception as e:
    print(f"An error occurred while loading the dataset: {e}")

"""Sekarang data `Advertising Budget and Sales.csv` telah berhasil dimuat ke dalam DataFrame bernama `df`. Mari kita mulai menganalisis datanya untuk melihat apakah data ini dapat digunakan untuk membuat model prediksi pengeluaran iklan."""

# Display basic information about the DataFrame
display(df.info())

# Display descriptive statistics
display(df.describe())

# Check for missing values
display(df.isnull().sum())

import pandas as pd

# Convert 'Date' column to datetime objects
df['Date'] = pd.to_datetime(df['Date'])

# Extract time-based features from 'Date'
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek # Monday=0, Sunday=6
df['WeekOfYear'] = df['Date'].dt.isocalendar().week.astype(int)

# Drop the original 'Date' column as we've extracted its information
df = df.drop(columns=['Date'])

print("Time-based features extracted and original 'Date' column dropped.")
display(df.head())

# Perform one-hot encoding for 'Brand Name' and 'Country' categorical columns
df = pd.get_dummies(df, columns=['Brand Name', 'Country'], drop_first=True)

print("One-hot encoding applied to 'Brand Name' and 'Country'.")
display(df.head())

# Update feature_columns to include newly created features and remove original categorical columns
# Also ensure 'Total Ad Spend' (target) is not in features.
target_column = 'Total Ad Spend'
feature_columns = [col for col in df.columns if col != target_column]

X = df[feature_columns]
y = df[target_column]

print(f"\nUpdated Feature variables: {feature_columns}")
print(f"Shape of updated features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets with the updated X and y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
model = LinearRegression()

# Train the model using the training data (X_train and y_train have been updated)
model.fit(X_train, y_train)

print("Linear Regression model re-trained successfully with engineered features.")

# Make predictions on the test set
y_pred = model.predict(X_test)

print("\nFirst 5 predictions:")
print(y_pred[:5])
print("\nFirst 5 actual values:")
print(y_test.head())

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Calculate evaluation metrics with the new predictions
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

"""Berdasarkan informasi di atas, kita bisa melihat ringkasan DataFrame, statistik deskriptif, dan mengecek nilai yang hilang. Ini adalah langkah awal untuk menentukan kesesuaian data untuk model prediksi.

Berdasarkan informasi di atas, kita bisa melihat ringkasan DataFrame, statistik deskriptif, dan mengecek nilai yang hilang. Ini adalah langkah awal untuk menentukan kesesuaian data untuk model prediksi.

Based on the output above, please identify the actual data file (e.g., `advertisement.csv`, `data.xlsx`) that the notebook intends to use. Once you identify the file, I can help you load it into a pandas DataFrame for further analysis.

Now that the data is downloaded and extracted, please examine the file list above and identify the main CSV file containing the dataset for ad campaign analysis. Once identified, I can help you load it into a pandas DataFrame.
"""